### ISSUE TITLE
disgord bug

### ISSUE THREAD

**Issue by andersfylling** [jfoster/discord-set-slowmode-bot#2]
Hi, I've been using your bot lately as I use slow mode on almost all my channels.
I also realized there was a cache issue on how channels were stored, that caused a nil panic. I patched that up in v0.9.6. But the patch won't be up for v0.8, so the only fix I know of for v0.8 bots is to use `disgord.GetChannel(..)` to bypass the cache completely.

Nice work on the bot!

**Comment by jfoster** [comment]
I'd actually had encountered that exact issue you describe which seemed to
coincide with my upgrade to v0.9.x, had temporarily reverted to v0.8.x for
the time being and had planned to investigate and submit an issue.

I see I had used discord.GetChannel() with dg v0.8.x which perfectly
explains why the previous build was working.

Cheers for fixing it and letting me know, I'll now see about re-reverting
the project and upgrading discord to v0.9.6, thanks for the hard work!
