### ISSUE TITLE
Upgrade disgord version

### ISSUE THREAD

**Issue by andersfylling** [jfoster/discord-set-slowmode-bot#3]
Hi, just notifying that Discord decided to do a breaking change to their API that takes place within less than a month. Because of this I suggest upgrading to v0.11 (the latest release) such that your application does not cease to function. Sorry about the inconvenience!

Source: https://github.com/discordapp/discord-api-docs/pull/967

**Comment by andersfylling** [comment]
Ops: v0.10.4 should also support this, in case upgrading from v0.10 to v0.11 causes issues.

**Comment by jfoster** [comment]
Thanks for the heads up!

Fixed in commit a25be55 and release v0.0.7
