### ISSUE TITLE
[Bug; v0.1.0] Bot does not load properly after attempting to execute with PowerShell

### ISSUE THREAD

**Issue by angelyurii** [jfoster/discord-set-slowmode-bot#5]
/title

I get this really extensive error when attempting to load the bot in PowerShell after shift-right-clicking the folder and opening the folder with it and using `./discord-set-slowmode-bot` in the window.
![image](https://user-images.githubusercontent.com/34490428/62672010-0816e900-b967-11e9-8a8c-dc2ed0983b7c.png)
Any support on this is appreciated. As mentioned in the title, I am using [release v0.1.0](https://github.com/jfoster/discord-set-slowmode-bot/releases/tag/v0.1.0) from this repo.

**Comment by jfoster** [comment]
Thank you for the detailed report, the stack trace points towards the client.CreateBotURL() method in DisGord.
I've now pushed a commit to workaround the issue and will push a patch release soon. Cheers 👍

**Comment by andersfylling** [comment]
That's super weird. I have no idea why that error happened as a location is hardcoded :thinking: 

Anyways, after seeing this error I've deprecated the method and wrote a new one that removes that time check completely. Please notify if you find any other DisGord issues! :)

**Comment by jfoster** [comment]
Apologies for not notifying you @andersfylling! Was going to try do some digging before submitting an issue but never got around to it and then forgot about it :see_no_evil:
